# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83df5045d56a8f011588943791a70e5b3ebc2e8795e1b71d7bcec3253839bb40c97273d1dc0a4dce03b9774845ebdba6441710cd1bd1d0710f7215c6357d7a73

test:
  secret_key_base: d8508ae5734d677dde111ec9c9cb4cf76f42668b30b9efe9306bda418225931269956ff6cf28aabb61f69627332e8d89c7679732cb5cfefaedf683cad4a12032

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
